### ISSUE TITLE
Get Error

### ISSUE THREAD

**Issue by kingnarias** [adamelso/albumgrab#1]
When I try to download the pictures i get the following error:

  [InvalidArgumentException]  
  The current node list is empty. 

can you help?

**Comment by adamelso** [comment]
Hi @kingnarias Do you know which line number you get the error on? Could you run the same command again with `--verbose` option appended?

**Comment by adamelso** [comment]
That being:

```
./albumgrab --verbose
```

**Comment by kingnarias** [comment]
May this example will help?

:~/albumgrab# ./albumgrab --verbose
Please enter the name of the directory your images will be saved to: /root/test123
Please enter the URL to the first image of the Facebook Photo Album you would like to download: https://www.facebook.com/photo.php?fbid=10101958277797391&set=pb.4.-2207520000.1425809258.
Opening https://www.facebook.com/photo.php?fbid=10101958277797391&set=pb.4.-2207520000.1425809258.
Image found https://fbcdn-sphotos-f-a.akamaihd.net/hphotos-ak-xfa1/v/t1.0-9/s720x720/11043000_10101958277797391_6381691121422178469_n.jpg?oh=b6d561cebe9614cd6e2b20eda7934018&oe=557641CA&__gda__=1433904532_52e8c8cac0d328b95757ca3a02664a5a
1

  [InvalidArgumentException]  
  The current node list is empty.  

Exception trace:
 () at /root/albumgrab/vendor/symfony/dom-crawler/Symfony/Component/DomCrawler/Crawler.php:690
 Symfony\Component\DomCrawler\Crawler->link() at /root/albumgrab/src/Command/DownloadAlbumCommand.php:78
 ArchFizz\Facebook\AlbumDownloader\Command\DownloadAlbumCommand->execute() at /root/albumgrab/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:252
 Symfony\Component\Console\Command\Command->run() at /root/albumgrab/vendor/symfony/console/Symfony/Component/Console/Application.php:894
 Symfony\Component\Console\Application->doRunCommand() at /root/albumgrab/vendor/symfony/console/Symfony/Component/Console/Application.php:193
 Symfony\Component\Console\Application->doRun() at /root/albumgrab/vendor/symfony/console/Symfony/Component/Console/Application.php:124
 Symfony\Component\Console\Application->run() at /root/albumgrab/albumgrab:30

download

**Comment by adamelso** [comment]
Ahhhh... So the error occurs because it cannot find a link called _Next_. It is possible that you are browsing Facebook in a language other than English?

In the meantime, I'll edit the code to allow you to find a link that's labelled differently.

**Comment by adamelso** [comment]
@kingnarias I've merged a fix [here](https://github.com/adamelso/albumgrab/pull/2).

Please let me know if it works. Cheers.
